# Generated by Django 4.2.11 on 2024-04-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sensor_1', models.IntegerField()),
                ('sensor_2', models.IntegerField()),
                ('temperature', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('pump_1', models.BooleanField()),
                ('pump_2', models.BooleanField()),
                ('update_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SettingTable',
            fields=[
                ('id', models.FloatField(primary_key=True, serialize=False)),
                ('minsensor_1', models.FloatField()),
                ('maxsensor_1', models.FloatField()),
                ('minsensor_2', models.FloatField()),
                ('maxsensor_2', models.FloatField()),
                ('plant_1', models.CharField(blank=True, max_length=100, null=True)),
                ('plant_2', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
