# Generated by Django 4.2.11 on 2024-04-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.FloatField(primary_key=True, serialize=False)),
                ('sensor_1', models.FloatField()),
                ('sensor_2', models.FloatField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('pump_1', models.FloatField()),
                ('pump_2', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SettingTable',
            fields=[
                ('id', models.FloatField(primary_key=True, serialize=False)),
                ('minsensor_1', models.FloatField()),
                ('maxsensor_1', models.FloatField()),
                ('minsensor_2', models.FloatField()),
                ('maxsensor_2', models.FloatField()),
            ],
        ),
    ]
