# Generated by Django 4.2.11 on 2024-04-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moisture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
