# Generated by Django 4.2.11 on 2024-04-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moisture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datatable',
            name='plant_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datatable',
            name='plant_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='humidity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='pump_1',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='pump_2',
            field=models.BooleanField(),
        ),
    ]
