# Generated by Django 4.2.11 on 2024-04-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moisture', '0002_datatable_plant_1_datatable_plant_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datatable',
            name='plant_1',
        ),
        migrations.RemoveField(
            model_name='datatable',
            name='plant_2',
        ),
        migrations.AddField(
            model_name='settingtable',
            name='plant_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='settingtable',
            name='plant_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
