# Generated by Django 4.2.11 on 2024-04-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moisture', '0002_alter_datatable_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
