# Generated by Django 4.2.11 on 2024-04-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moisture', '0003_remove_datatable_plant_1_remove_datatable_plant_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatable',
            name='sensor_1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='sensor_2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='datatable',
            name='temperature',
            field=models.IntegerField(),
        ),
    ]
